"""Deterministic Herald Intro / Outro Branding Module.

Programmatically generates application-owned branded intro and outro narration.
These strings are NEVER sent to or generated by an LLM model.
"""

import html
import logging
import re
from pathlib import Path
from typing import Any

from herald.audio.ffmpeg_builder import inspect_pcm_wav_file, validate_audio_file
from herald.config import settings
from herald.tts.kokoro_client import KokoroClient

logger = logging.getLogger("herald.audio.branding")

INTRO_FIXED_TEMPLATE = (
    "This is Herald, an open-source podcast generation platform. "
    "You're listening to an approximately {target_minutes}-minute podcast about {topic}. Enjoy."
)

INTRO_GENERAL_TEMPLATE = (
    "This is Herald, an open-source podcast generation platform. "
    "You're listening to a podcast about {topic}. Enjoy."
)

OUTRO_TEMPLATE = "You've been listening to Herald, the open-source podcast generation platform."


def sanitize_branding_topic(raw_topic: str | None, max_chars: int = 80) -> str:
    """
    Sanitize and normalize a topic string for natural-sounding speech in the intro.
    Strips markdown, HTML tags, excess whitespace, URL protocols, and trailing punctuation.
    """
    if not raw_topic:
        return "today's topic"

    clean = raw_topic.strip()
    # Remove HTML tags if present
    clean = re.sub(r"<[^>]+>", "", clean)
    clean = html.unescape(clean)
    # Remove markdown bold/italic/backticks/links
    clean = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", clean)
    clean = re.sub(r"[*_`#~]", "", clean)
    # Remove leading/trailing quotes and punctuation
    clean = clean.strip(" '\"`.,:;!?–—()[]{}")
    # Collapse multiple whitespace
    clean = re.sub(r"\s+", " ", clean).strip()

    if not clean:
        return "today's topic"

    if len(clean) > max_chars:
        # Bounded truncation at word boundary
        truncated = clean[:max_chars].rsplit(" ", 1)[0].strip()
        clean = truncated or clean[:max_chars]

    return clean or "today's topic"


def render_intro_narration(topic: str | None, target_minutes: str | int | None) -> str:
    """
    Render deterministic intro narration string.
    Uses INTRO_FIXED_TEMPLATE when target_minutes is a specific duration (e.g. 10, 20, 30, 45, 60),
    and INTRO_GENERAL_TEMPLATE for 'auto', 'literal', or unspecified duration.
    """
    clean_topic = sanitize_branding_topic(topic)
    t_str = str(target_minutes).lower().strip() if target_minutes is not None else ""

    if t_str and t_str.isdigit() and int(t_str) > 0:
        return INTRO_FIXED_TEMPLATE.format(target_minutes=t_str, topic=clean_topic)

    return INTRO_GENERAL_TEMPLATE.format(topic=clean_topic)


def render_outro_narration() -> str:
    """Render deterministic outro narration string."""
    return OUTRO_TEMPLATE


def synthesize_branding_segment(
    text: str,
    output_wav_path: Path,
    kokoro_client: KokoroClient,
    voice: str,
    speed: float = 1.0,
    segment_name: str = "branding",
) -> dict[str, Any]:
    """
    Synthesize an intro or outro narration segment into a validated WAV file using Kokoro.
    Adheres to normal WAV validation rules and returns duration metadata.
    """
    output_wav_path.parent.mkdir(parents=True, exist_ok=True)
    logger.info(f"Synthesizing {segment_name} narration segment ({len(text)} chars)")

    res = kokoro_client.synthesize_wav(
        text=text,
        output_path=output_wav_path,
        voice=voice,
        speed=speed,
    )
    validate_audio_file(output_wav_path)
    info = inspect_pcm_wav_file(output_wav_path)
    dur = info["duration_seconds"] if info else getattr(res, "audio_duration", 0.0)

    return {
        "path": output_wav_path,
        "duration_seconds": float(dur),
        "text": text,
        "voice": voice,
        "speed": speed,
    }
