"""Deterministic Herald Intro / Outro Branding Module.

Programmatically generates application-owned branded intro and outro narration.
These strings are NEVER sent to or generated by an LLM model.
"""

import html
import json
import logging
import re
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

from herald.audio.ffmpeg_builder import inspect_pcm_wav_file, validate_audio_file
from herald.config import settings
from herald.tts.chunk_manager import compute_chunk_text_hash
from herald.tts.kokoro_client import KokoroClient
from herald.tts.lexicon import PronunciationLexicon
from herald.tts.normalizer import normalize_for_speech

logger = logging.getLogger("herald.audio.branding")

INTRO_EPISODE_TEMPLATE = "This is {platform_name}. Today's episode is '{episode_title}'."
INTRO_EPISODE_DURATION_TEMPLATE = (
    "This is {platform_name}. Today's episode is '{episode_title}', running approximately {target_minutes} minutes."
)
INTRO_REPORTING_TEMPLATE = "Based on reporting from {publisher}."
INTRO_CLOSING = "Let's begin."

INTRO_FIXED_TEMPLATE = (
    "This is {platform_name}. Today's episode is '{topic}', running approximately {target_minutes} minutes. Let's begin."
)

INTRO_GENERAL_TEMPLATE = (
    "This is {platform_name}. Today's episode is '{topic}'. Let's begin."
)

OUTRO_TEMPLATE = "You've been listening to {platform_name}, the open-source podcast generation platform."


def sanitize_publisher_name(raw_publisher: str | None) -> str | None:
    """Sanitize publisher name to prevent dangling phrases, URLs, or malformed attribution."""
    if not raw_publisher:
        return None
    clean = str(raw_publisher).strip()
    if "://" in clean or clean.startswith("www."):
        try:
            clean = urlparse(clean if "://" in clean else f"https://{clean}").netloc.replace("www.", "")
        except Exception:
            return None

    clean = re.sub(r"<[^>]+>", "", clean)
    clean = re.sub(r"[*_`#~]", "", clean)
    clean = clean.strip(" '\"`.,:;!?–—()[]{}")
    clean = re.sub(r"\s+", " ", clean).strip()

    if not clean or clean.lower() in ("at", "enjoy", "http", "https", "www", "unknown", "n/a", "none", "today's topic"):
        return None
    return clean


def sanitize_branding_topic(raw_topic: str | None, max_chars: int = 80) -> str:
    """Sanitize and normalize an episode title or topic string for natural speech.

    Strips raw URLs, protocols, domains, query strings, file extensions,
    markdown formatting, HTML tags, excess whitespace, and trailing punctuation.
    """
    if not raw_topic:
        return "today's topic"

    clean = raw_topic.strip()

    # Check if raw_topic looks like a URL
    if clean.startswith("http://") or clean.startswith("https://") or clean.startswith("www."):
        try:
            parsed = urlparse(clean if "://" in clean else f"https://{clean}")
            path = parsed.path.strip("/")
            if path:
                path_clean = re.sub(r"\.[a-zA-Z0-9]+$", "", path)
                path_segments = [p for p in path_clean.strip("/").split("/") if p and not p.isdigit()]
                if path_segments:
                    slug = path_segments[-1]
                    words = [w for w in re.split(r"[-_]+", slug) if w]
                    clean = " ".join(words).title()
                else:
                    clean = parsed.netloc.replace("www.", "").split(".")[0].title()
            else:
                clean = parsed.netloc.replace("www.", "").split(".")[0].title()
        except Exception:
            clean = "today's topic"

    # Remove HTML tags if present
    clean = re.sub(r"<[^>]+>", "", clean)
    clean = html.unescape(clean)
    # Remove markdown bold/italic/backticks/links
    clean = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", clean)
    clean = re.sub(r"[*_`#~]", "", clean)
    # Remove leading/trailing quotes and punctuation
    clean = clean.strip(" '\"`.,:;!?–—()[]{}")
    # Collapse multiple whitespace
    clean = re.sub(r"\s+", " ", clean).strip()

    if not clean or clean.lower() in ("http", "https", "www"):
        return "today's topic"

    if len(clean) > max_chars:
        truncated = clean[:max_chars].rsplit(" ", 1)[0].strip()
        clean = truncated or clean[:max_chars]

    return clean or "today's topic"


def render_intro_narration(
    topic: str | None = None,
    target_minutes: str | int | None = None,
    actual_body_duration_seconds: float | None = None,
    content_mode: str | None = None,
    episode_title: str | None = None,
    publisher: str | None = None,
    source_title: str | None = None,
    research_depth: str | None = None,
    request_mode: str | None = None,
) -> str:
    """Render deterministic intro narration string describing generation mode without runtime estimate.

    Format examples:
    - Research-topic episode:
      "Herald presents: The Birth of the Nuclear Submarine. This episode was generated from a research topic using medium research depth. Let's begin."
    - Source/article episode:
      "Herald presents: The Birth of the Nuclear Submarine. This episode was generated from a submitted source. Based on reporting from [Publisher]. Let's begin."
    - Source + supplemental research:
      "Herald presents: The Birth of the Nuclear Submarine. This episode was generated from a submitted source with medium research. Let's begin."
    - Literal mode:
      "Herald presents: The Birth of the Nuclear Submarine. This episode was generated directly from a submitted source. Let's begin."
    """
    platform_name = getattr(settings, "BRANDING_PLATFORM_NAME", "Herald")
    raw_title = episode_title or source_title or topic
    clean_title = sanitize_branding_topic(raw_title)

    clean_pub = sanitize_publisher_name(publisher)

    lead = f"{platform_name} presents: {clean_title}."

    c_mode = (content_mode or request_mode or "source").lower().strip()
    depth_str = (research_depth or "medium").lower().strip()

    if c_mode in ("topic", "research"):
        desc = f"This episode was generated from a research topic using {depth_str} research depth."
    elif c_mode == "expanded":
        desc = f"This episode was generated from a submitted source with {depth_str} research."
    elif c_mode == "literal":
        desc = "This episode was generated directly from a submitted source."
    else:  # source mode
        desc = "This episode was generated from a submitted source."

    parts = [lead, desc]
    if clean_pub:
        parts.append(INTRO_REPORTING_TEMPLATE.format(publisher=clean_pub))
    parts.append(INTRO_CLOSING)

    return " ".join(parts)


def render_outro_narration() -> str:
    """Render deterministic outro narration string."""
    platform_name = getattr(settings, "BRANDING_PLATFORM_NAME", "Herald")
    return OUTRO_TEMPLATE.format(platform_name=platform_name)


def synthesize_branding_segment(
    text: str,
    output_wav_path: Path,
    kokoro_client: KokoroClient,
    voice: str,
    speed: float = 1.0,
    segment_name: str = "branding",
    lexicon: PronunciationLexicon | None = None,
    spoken_text: str | None = None,
    timeout: float | None = None,
    global_semaphore: Any = None,
) -> dict[str, Any]:
    """Synthesize an intro or outro narration segment into a validated WAV file using Kokoro.

    Normalizes canonical branding text deterministically for speech, reuses
    KokoroClient.synthesize_chunk, respects global TTS concurrency semaphore,
    supports restart-safe cache validation against spoken text hash, and validates
    resulting audio.
    """
    output_wav_path.parent.mkdir(parents=True, exist_ok=True)

    # 1. Deterministic spoken text normalization
    transformations: list[dict[str, str]] = []
    if spoken_text is None:
        norm_res = normalize_for_speech(text, lexicon=lexicon)
        effective_spoken = norm_res.spoken_text
        transformations = [t.to_dict() for t in norm_res.transformations]
    else:
        effective_spoken = spoken_text

    # 2. Compute authoritative versioned cache hash
    spoken_hash = compute_chunk_text_hash(effective_spoken, voice=voice, speed=speed)
    meta_path = output_wav_path.with_suffix(".meta.json")

    # Restart-safe check: reuse existing valid WAV file if already present and hash matches
    if output_wav_path.exists() and output_wav_path.stat().st_size > 0:
        cache_valid = False
        if meta_path.exists():
            try:
                meta = json.loads(meta_path.read_text(encoding="utf-8"))
                if meta.get("text_hash") == spoken_hash:
                    cache_valid = True
            except Exception:
                cache_valid = False
        else:
            # If no meta file exists, check if filename itself embeds the hash
            if spoken_hash[:8] in output_wav_path.stem:
                cache_valid = True

        if cache_valid:
            try:
                validate_audio_file(output_wav_path)
                info = inspect_pcm_wav_file(output_wav_path)
                if info and info.get("duration_seconds", 0) > 0:
                    logger.info(
                        f"Reusing existing valid {segment_name} audio chunk ({info['duration_seconds']:.1f}s) at {output_wav_path}"
                    )
                    return {
                        "path": output_wav_path,
                        "duration_seconds": float(info["duration_seconds"]),
                        "canonical_text": text,
                        "text": text,
                        "spoken_text": effective_spoken,
                        "transformations": transformations,
                        "text_hash": spoken_hash,
                        "voice": voice,
                        "speed": speed,
                    }
            except Exception:
                logger.debug(f"Existing {segment_name} audio invalid or unreadable, re-synthesizing...")

    logger.info(f"Synthesizing {segment_name} narration segment ({len(effective_spoken)} chars)")

    if global_semaphore is not None:
        with global_semaphore:
            kokoro_client.synthesize_chunk(
                text=effective_spoken,
                output_path=output_wav_path,
                voice=voice,
                speed=speed,
                timeout=timeout,
            )
    else:
        kokoro_client.synthesize_chunk(
            text=effective_spoken,
            output_path=output_wav_path,
            voice=voice,
            speed=speed,
            timeout=timeout,
        )

    validate_audio_file(output_wav_path)
    info = inspect_pcm_wav_file(output_wav_path)
    dur = info["duration_seconds"] if info else 0.0

    # Write companion metadata for cache validation
    try:
        meta_data = {
            "text_hash": spoken_hash,
            "canonical_text": text,
            "spoken_text": effective_spoken,
            "transformations": transformations,
            "voice": voice,
            "speed": speed,
            "duration_seconds": float(dur),
        }
        meta_path.write_text(json.dumps(meta_data, indent=2), encoding="utf-8")
    except Exception as me:
        logger.debug(f"Could not write branding meta file: {me}")

    return {
        "path": output_wav_path,
        "duration_seconds": float(dur),
        "canonical_text": text,
        "text": text,
        "spoken_text": effective_spoken,
        "transformations": transformations,
        "text_hash": spoken_hash,
        "voice": voice,
        "speed": speed,
    }
